language: go

go:
    - 1.6

install: true
before_script: true

script:
    - ./build_all.sh

before_deploy:
    - export DEBUG_LS=$(ls .build/)
    - echo $DEBUG_LS

deploy:
    provider: releases
    api_key: $GH_TOKEN
    file:
        - .build/getIE
        - .build/getIE.app
        - .build/getIE.exe
    skip_cleanup: true
    on:
        tags: true
        all_branches: true
