language: go

go:
    - 1.6

install: true
before_script: true

script:
    - ./build_all.sh

deploy:
    provider: releases
    api_key: $GH_TOKEN
    file:
        - "$HOME/gopath/src/github.com/artemdevel/getIE/.build/getIE"
        - "$HOME/gopath/src/github.com/artemdevel/getIE/.build/getIE.app"
        - "$HOME/gopath/src/github.com/artemdevel/getIE/.build/getIE.exe"
    skip_cleanup: true
    on:
        tags: true
        all_branches: true
