language: go

go:
    - 1.6

install: true
before_script: true

script:
    - ./build_all.sh

deploy:
    provider: releases
    api_key: "efb98faa9f44e70582185a4713714bcdf85e82a8"
    file:
        - .build/getIE
        - .build/getIE.app
        - .build/getIE.exe
    skip_cleanup: true
    on:
        tags:
            - alpha-1.0.0
            - alpha-2.0.0
